#!/usr/bin/env bash
# list all my currently running processes
# Displays a list of currently running processes.
#   Shows all processes, for all users, including those
#+  which might not have a TTY.

ps -auxf
